/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_user_files_s3_bucket": "YOUR_S3_BUCKET",
    "aws_user_files_s3_bucket_region": "YOUR_REGION",
    "aws_appsync_graphqlEndpoint": "YOUR_GRAPHQL_ENDPOINT",
    "aws_appsync_region": "YOUR_REGION"
};

export default awsmobile;